    # 1. Update config values (localhost --> mongo and localhost --> redis) in config.development.json
    # 2. Set APP_ENV environment variable to proper value in Dockerfile-redis (default is "development")
    #    export APP_ENV=development
    #    export DOCKER_ACCT=<yourHubUserName>
    # 3. Run docker-compose build
    # 4. Run docker-compose up
    # 5. Live long and prosper
    
version: "3.1"
 
services:
    drupal8:
      container_name: drupal8
      build: 
        context: .
        dockerfile: .docker/php-drupal8.production.dockerfile
      ports:
      - 80:80
      - 443:443
      networks:
        - drupal8-network

    mysql:
      container_name: mysql
      image: mysql
      restart: always
      env_file:
              - ./.docker/env/mysql.production.env
      networks:
        - drupal8-network
        - adminer-network

    adminer:
      container_name: adminer
      image: adminer
      restart: always
      ports:
          - 9090:8080
      networks:
        - adminer-network
        
networks:
  drupal8-network:
    driver: bridge
  adminer-network:
    driver: bridge